### ISSUE TITLE
Doesn't Work in Windows....

### ISSUE THREAD

**Issue by Suleman-Elahi** [fredyshox/PDFColorSwap#3]
I think is not compatible with Windows 10 ?

**Comment by fredyshox** [comment]
Looks like there is a problem with Windows file paths. Latest commit should resolve this but I will leave it until I do some further testing on Windows machines.

**Comment by Suleman-Elahi** [comment]
I think this may help.............
![image](https://user-images.githubusercontent.com/24384996/43697792-21cfa4b4-9964-11e8-9ce6-9a5c7ac1f585.png)
